# ==============================================================
# = Articoli Web Service - Profilo std
# ==============================================================

spring:
# ==============================================================
# = Cloud Parameters
# ==============================================================
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
# ==============================================================
# = DBMS PostgreSQL Parameters
# ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/Shop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

# ==============================================================
# = Proprietà RabbitMQ
# ==============================================================      
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: rabbitmq   
# ==============================================================
# = Feign Parameters
# ============================================================== 
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    connection-timeout: 3000
  client:
    config:
      default:
        connectTimeout: 300000 #5 MINUTI
        readTimeout: 300000

# ==============================================================
# = RIBBON
# ==============================================================
#PriceArtWebService:
#  ribbon:
#   listOfServers: http://localhost:5071,http://localhost:5072,http://localhost:5073

# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics,hystrix.stream
        
# ==============================================================
# = ACTUATOR INFO
# ==============================================================
info:
  assistenza:
    nome: "Umberto Ornaghi"
    mail: "umberto.ornaghi@gmail.com"
  nome:
    nome-app: "Articoli web service con JWT"

# ==============================================================
# = Proprietà Logging
# = Default ERROR, WARN e INFO 
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ============================================================== 
logging:
  file:
    name: ArtSrv.log
    max-size: 1MB
    #path: "/logs"
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n"
    #console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    
  # Livello del Log generale
  level:
   root: INFO
  # Livello di log specifico
   org.springframework.security: DEBUG
   org.hibernate: INFO
   org.springframework.web: INFO
   com.xantrix.webapp.controller: INFO
   org.springframework.cloud: ERROR
    
# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================          
gestuser:
  password: password
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella
